name: Build and Deploy to Docker Hub

on: 
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    # Log in to Docker Hub using credentials stored in GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile.web
        push: true
        tags: tarikanowarcr7/wechathub:latest, tarikanowarcr7/wechathub:${{ github.sha }}

    # Deploy to EC2 server using SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Install Docker if not already installed
          if ! command -v docker &> /dev/null
          then
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi
          
          # Remove unused Docker images
          sudo docker system prune -f
          
          # Pull the latest Docker image and run the web app
          sudo docker pull tarikanowarcr7/wechathub:${{ github.sha }}
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d \
            -e DATABASE_URL=${{ secrets.DB_URL }} \
            -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e PROJECT_ENVIRONMENT=${{ secrets.PROJECT_ENVIRONMENT }} \
            --name web-app -p 3000:3000 tarikanowarcr7/wechathub:${{ github.sha }}

          # Check logs to confirm the container is running correctly
          sudo docker logs web-app
