name: Build and Deploy to Docker Hub

on: 
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tarikanowarcr7
        password: dckr_pat_n9XHwwU2jJ9RekIlth6X8a4RcHI

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: tarikanowarcr7/wechathub

    - name: Verify Pushed Image
      run: docker pull tarikanowarcr7/wechathub
